import { DBMember, DBChat, DBNotification } from "./schema";
import { Member, TrainingArt } from "../types/member";

export const dummyMembers: DBMember[] = [
  {
    id: "1",
    username: "johndoe",
    email: "john@example.com",
    password_hash: "hashed_password_1",
    profile_photo: "https://i.pravatar.cc/300?img=11",
    date_of_birth: "1990-01-01",
    training_start_date: "2020-06-15",
    training_arts: ["BJJ", "Wrestling", "Submission Grappling"],
    bio: "Passionate about BJJ and always learning",
    gender: "male",
    weight_value: 75,
    weight_unit: "kg",
    height_value: 175,
    height_unit: "cm",
    privacy_settings: {
      age_visibility: true,
      weight_visibility: true,
      height_visibility: true,
      connections_visibility: true,
    },
    membership_status: "free",
    account_status: "active",
    is_online: true,
    last_active: new Date().toISOString(),
    created_at: "2023-01-01T00:00:00Z",
    updated_at: "2023-01-01T00:00:00Z",
  },
  {
    id: "2",
    username: "sarahsmith",
    email: "sarah@example.com",
    password_hash: "hashed_password_2",
    profile_photo: "https://i.pravatar.cc/300?img=47",
    date_of_birth: "1992-03-15",
    training_start_date: "2019-01-10",
    training_arts: ["BJJ", "Wrestling"],
    bio: "Wrestling background, now focused on BJJ",
    gender: "female",
    weight_value: 63,
    weight_unit: "kg",
    height_value: 165,
    height_unit: "cm",
    privacy_settings: {
      age_visibility: true,
      weight_visibility: true,
      height_visibility: true,
      connections_visibility: true,
    },
    membership_status: "paid",
    account_status: "active",
    is_online: true,
    last_active: new Date().toISOString(),
    created_at: "2023-01-02T00:00:00Z",
    updated_at: "2023-01-02T00:00:00Z",
  },
  {
    id: "3",
    username: "mikebrown",
    email: "mike@example.com",
    password_hash: "hashed_password_3",
    profile_photo: "https://i.pravatar.cc/300?img=68",
    date_of_birth: "1988-07-22",
    training_start_date: "2021-02-01",
    training_arts: ["Wrestling", "Submission Grappling"],
    bio: "New to grappling, loving the journey",
    gender: "male",
    weight_value: 82,
    weight_unit: "kg",
    height_value: 180,
    height_unit: "cm",
    privacy_settings: {
      age_visibility: true,
      weight_visibility: true,
      height_visibility: true,
      connections_visibility: true,
    },
    membership_status: "free",
    account_status: "suspended",
    is_online: false,
    last_active: "2024-01-20T15:30:00Z",
    created_at: "2023-01-03T00:00:00Z",
    updated_at: "2023-01-03T00:00:00Z",
  },
  {
    id: "4",
    username: "alexchen",
    email: "alex@example.com",
    password_hash: "hashed_password_4",
    profile_photo: "https://i.pravatar.cc/300?img=32",
    date_of_birth: "1995-11-03",
    training_start_date: "2018-05-20",
    training_arts: ["BJJ", "Wrestling", "Submission Grappling"],
    bio: "Competitive grappler, always looking to improve",
    gender: "male",
    weight_value: 70,
    weight_unit: "kg",
    height_value: 170,
    height_unit: "cm",
    privacy_settings: {
      age_visibility: true,
      weight_visibility: true,
      height_visibility: true,
      connections_visibility: true,
    },
    membership_status: "paid",
    account_status: "active",
    is_online: true,
    last_active: new Date().toISOString(),
    created_at: "2023-01-04T00:00:00Z",
    updated_at: "2023-01-04T00:00:00Z",
  }
];

export const dummyChats: DBChat[] = [
  {
    id: "1",
    sender_id: "2",
    receiver_id: "1",
    message: "Hey John, want to drill the new techniques before class?",
    is_read: false,
    created_at: "2024-01-20T10:00:00Z",
    updated_at: "2024-01-20T10:00:00Z",
  },
  {
    id: "2",
    sender_id: "2",
    receiver_id: "1",
    message: "I'll be there early around 5:30pm if that works for you.",
    is_read: false,
    created_at: "2024-01-20T10:05:00Z",
    updated_at: "2024-01-20T10:05:00Z",
  },
  {
    id: "3",
    sender_id: "3",
    receiver_id: "1",
    message: "Are you coming to open mat this weekend?",
    is_read: false,
    created_at: "2024-01-20T15:30:00Z",
    updated_at: "2024-01-20T15:30:00Z",
  },
  {
    id: "4",
    sender_id: "4",
    receiver_id: "1",
    message: "Great rolls today! That new guard pass really helped.",
    is_read: false,
    created_at: "2024-01-20T16:00:00Z",
    updated_at: "2024-01-20T16:00:00Z",
  }
];

export const dummyNotifications: DBNotification[] = [
  {
    id: "n1",
    recipient_id: "1",
    type: "direct_message",
    title: "Sarah Smith",
    message: "Hey John, want to drill the new techniques before class?",
    is_read: true, // This older message is read
    sender_id: "2",
    message_id: "1",
    target_route: "/chat/2?messageId=1",
    created_at: "2024-01-20T10:00:00Z",
    updated_at: "2024-01-20T10:00:00Z"
  },
  {
    id: "n2",
    recipient_id: "1",
    type: "direct_message",
    title: "Sarah Smith",
    message: "I'll be there early around 5:30pm if that works for you.",
    is_read: false, // Unread follow-up message
    sender_id: "2",
    message_id: "2",
    target_route: "/chat/2?messageId=2",
    created_at: "2024-01-20T10:05:00Z",
    updated_at: "2024-01-20T10:05:00Z"
  },
  {
    id: "n3",
    recipient_id: "1",
    type: "direct_message",
    title: "Mike Brown",
    message: "Are you coming to open mat this weekend?",
    is_read: false, // Unread message from different user
    sender_id: "3",
    message_id: "3",
    target_route: "/chat/3?messageId=3",
    created_at: "2024-01-20T15:30:00Z",
    updated_at: "2024-01-20T15:30:00Z"
  },
  {
    id: "n4",
    recipient_id: "1",
    type: "direct_message",
    title: "Alex Chen",
    message: "Great rolls today! That new guard pass really helped.",
    is_read: false, // Unread message from another user
    sender_id: "4",
    message_id: "4",
    target_route: "/chat/4?messageId=4",
    created_at: "2024-01-20T16:00:00Z",
    updated_at: "2024-01-20T16:00:00Z"
  }
];

// Helper function to convert DB member to frontend Member type
export const convertDBMemberToMember = (dbMember: DBMember): Member => ({
  id: dbMember.id,
  username: dbMember.username,
  profilePhoto: dbMember.profile_photo || null,
  email: dbMember.email,
  dateOfBirth: dbMember.date_of_birth,
  trainingStartDate: dbMember.training_start_date,
  trainingArts: dbMember.training_arts as TrainingArt[],
  bio: dbMember.bio,
  gender: dbMember.gender,
  weight: {
    value: dbMember.weight_value,
    unit: dbMember.weight_unit,
  },
  height: {
    value: dbMember.height_value,
    unit: dbMember.height_unit,
  },
  privacySettings: {
    ageVisibility: dbMember.privacy_settings.age_visibility,
    weightVisibility: dbMember.privacy_settings.weight_visibility,
    heightVisibility: dbMember.privacy_settings.height_visibility,
    connectionsVisibility: dbMember.privacy_settings.connections_visibility,
  },
  membershipStatus: dbMember.membership_status,
  accountStatus: dbMember.account_status,
  isOnline: dbMember.is_online,
  lastActive: dbMember.last_active,
});
